config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_for :teachers

  resources :teachers
  resources :students

  namespace :dashboard do
    root to: 'dashboard#index'
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
  has_many :teachers

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
end

app/models/student.rb
class Student < User
  belongs_to :school
end

app/models/teacher.rb
class Teacher < User
  belongs_to :school
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def fullname
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  devise_group :user, contains: %i[student teacher]

  private

  def after_sign_in_path_for(_resource)
    dashboard_root_path
  end

  protected

  def configure_permitted_parameters
    attributes = %i[first_name last_name school_id]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_school

  def index
    @teachers = @school.teachers
    @students = @school.students
  end

  private

  def set_school
    if current_teacher
      @school = current_teacher.school
    elsif current_student
      @school = current_student.school
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :verify_admin
  before_action :set_student, except: :new

  def new
    @student = Student.new
  end

  def edit
  end

  def update
    @student.update student_params
    if @student.save
      flash[:notice] = 'Student successfully updated.'
      redirect_to dashboard_root_path
    else
      flash[:error] = 'Student unable to be updated.'
      render 'edit'
    end
  end

  def destroy
    if @student.destroy
      flash[:notice] = 'Student successfully deleted.'
    else
      flash[:error] = 'Student unable to be deleted.'
    end
    redirect_to dashboard_root_path
  end

  private

  def set_student
    @student = Student.find params[:id]
  end

  def verify_admin
    unless current_teacher&.admin?
      flash[:error] = 'You are not an admin.'
      redirect_to dashboard_root_path
    end
  end

  def student_params
    params.require(:student).permit(:email, :last_name, :first_name, :school_id)
  end


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher!
  before_action :verify_admin
  before_action :set_teacher, except: :new

  def new
    @teacher = Teacher.new
  end

  def edit
  end

  def update
    @teacher.update teacher_params
    if @teacher.save
      flash[:notice] = 'Teacher successfully updated.'
      redirect_to dashboard_root_path
    else
      flash[:error] = 'Teacher unable to be updated.'
      render 'edit'
    end
  end

  def destroy
    if @teacher.destroy
      flash[:notice] = 'Teacher successfully deleted.'
    else
      flash[:error] = 'Teacher unable to be deleted.'
    end
    redirect_to dashboard_root_path
  end

  private

  def set_teacher
    @teacher = Teacher.find params[:id]
  end

  def verify_admin
    unless current_teacher&.admin?
      flash[:error] = 'You are not an admin.'
      redirect_to dashboard_root_path
    end
  end

  def teacher_params
    params.require(:teacher).permit(:email, :last_name, :first_name, :school_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when 'notice' then 'alert alert-info'
        when 'success' then 'alert alert-success'
        when 'error' then 'alert alert-error'
        when 'alert' then 'alert alert-error'
    end
  end
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/dashboard/dashboard/_students.html.haml
%table.table.table-striped
  %thead
    %th Name
    %th Email
    %th Actions
  %tbody
    - @students.each do |student|
      %tr
        %td= student.fullname
        %td= student.email
        %td
          = link_to 'Edit', edit_student_path(student),
                            method: :get,
                            class: 'btn btn-secondary btn-sm'
          = link_to 'Delete', student_path(student),
                              method: :delete,
                              data: { confirm: 'Are you sure?' },
                              class: 'btn btn-danger btn-sm'

app/views/dashboard/dashboard/_teachers.html.haml
%table.table.table-striped
  %thead
    %th Name
    %th Email
    %th Admin?
    %th Actions
  %tbody
    - @teachers.each do |teacher|
      %tr
        %td= teacher.fullname
        %td= teacher.email
        %td= teacher.admin?
        %td
          = link_to 'Edit', edit_teacher_path(teacher),
                            method: :get,
                            class: 'btn btn-secondary btn-sm'
          = link_to 'Delete', teacher_path(teacher),
                              method: :delete,
                              data: { confirm: 'Are you sure?' },
                              class: 'btn btn-danger btn-sm'

app/views/dashboard/dashboard/index.html.haml
%h1 Dashboard
- if student_signed_in?
  %p I'm a Student and I do not see anything here yet
- if teacher_signed_in?
  - unless current_teacher.admin?
    %p I'm a non Admin Teacher and I do not see anything here yet
  - else
    %h3 Teachers
    = link_to 'Add Teacher', new_teacher_path,
                         method: :get,
                         class: 'btn btn-primary float-right'
    = render 'teachers'
    %hr/
    %h3 Students
    = link_to 'Add Student', new_student_path,
                         method: :get,
                         class: 'btn btn-primary float-right'
    = render 'students'

app/views/home/index.html.haml
.col-sm-12
  .row
    .col-sm-6
      .card{:style => "width: 24rem;"}
        .card-body#teacher
          %h5.card-title Teacher Sign In
          %p.card-text If you are a teacher and already have an account, please sign in, otherwise sign up.
          = link_to 'Sign In', new_teacher_session_path, class: 'btn btn-primary'
          = link_to 'Sign Up', new_teacher_registration_path, class: 'btn btn-secondary'

    .col-sm-6
      .card{:style => "width: 24rem;"}
        .card-body#student
          %h5.card-title Student Sign In
          %p.card-text If you are a student and already have an account, please sign in, otherwise sign up.
          = link_to 'Sign In', new_student_session_path, class: 'btn btn-primary'
          = link_to 'Sign Up', new_student_registration_path, class: 'btn btn-secondary'

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{class: flash_class(key)}
    = value

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"} BookRepo
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item.active
        %a.nav-link{:href => "/"}
          Home
          %span.sr-only (current)
      %li.nav-item
        - if current_user
          = link_to 'Dashboard', dashboard_root_path, class: 'nav-link'
      %li.nav-item
        - if student_signed_in?
          = link_to 'Log out', destroy_student_session_path, method: :delete, class: 'nav-link'
        - if teacher_signed_in?
          = link_to 'Log out', destroy_teacher_session_path, method: :delete, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bookrepo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/nav'
    = render 'layouts/messages'
    .container.pt-4
      = yield

app/views/students/edit.html.haml
.col-md-8.offset-md-2
  %h2 Edit Student
  = simple_form_for @student, method: :patch do |f|
    = f.input :email
    = f.input :first_name
    = f.input :last_name
    = f.input :school_id, collection: School.all
    = f.submit class: 'btn btn-primary'

app/views/students/new.html.haml
.col-md-8.offset-md-2
  %h2 New Student
  = simple_form_for @student, method: :post do |f|
    = f.input :email
    = f.input :first_name
    = f.input :last_name
    = f.input :password
    = f.input :password_confirmation
    = f.input :school_id, collection: School.all
    = f.submit class: 'btn btn-primary'

app/views/teachers/edit.html.haml
.col-md-8.offset-md-2
  %h2 Edit Teacher
  = simple_form_for @teacher, method: :patch do |f|
    = f.input :email
    = f.input :first_name
    = f.input :last_name
    = f.input :school_id, collection: School.all
    = f.submit class: 'btn btn-primary'

app/views/teachers/new.html.haml
.col-md-8.offset-md-2
  %h2 New Teacher
  = simple_form_for @teacher, method: :post do |f|
    = f.input :email
    = f.input :first_name
    = f.input :last_name
    = f.input :password
    = f.input :password_confirmation
    = f.input :school_id, collection: School.all
    = f.submit class: 'btn btn-primary'